language: node_js
node_js:
  - "8"
  - "10"
before_install:
  - npm install -g yarn
notifications:
  email: false
deploy:
  provider: script
  script: ./scripts/publish.sh
  on:
    tags: true
    node: 10
  skip_cleanup: true
